### ISSUE TITLE
Update README with GitHub Actions?

### ISSUE THREAD

**Issue by jsjoeio** [IBM/audit-ci#179]
Thanks for making this! :)

Would it be possible for you to add an example for GitHub Actions to the `README.md`?

Maybe something like:

```yaml
    steps:
      - uses: actions/checkout@v2
      - name: Audit for vulnerabilities
        run: npx audit-ci --moderate
```

If that's right, I'm happy to open a PR as well.
